import Head from 'next/head'
import Image from 'next/image'
import logo from '../images/logo-aqua.svg'
import { FaPlus, FaTimes } from "react-icons/fa";
import { useState } from 'react';
export default function Home() {
  const [todo, setTodo] = useState([]);
  const handleEntailmentRequest = (e) => {
    e.preventDefault();
    if (e.target[0].value.trim() === "") {
    }
    else {
      setTodo([...todo, e.target[0].value.trim()]);
    }
    e.target[0].value = '';
  }

  const deleteTodo = (i) => {
    const newTodo = [...todo];
    newTodo.splice(i, 1);
    setTodo(newTodo);
  }
  const complateTodo = (i) => {
    const liElement = i.target;
    if (liElement.classList.contains("line-through")) {
      liElement.classList.remove("line-through");
    } else {
      liElement.classList.add("line-through");
    }
  };
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
      </Head>
      <main className='w-full h-screen bg-[#F0EFE9] flex flex-col items-center justify-center font-poppins'>
        <Image
          src={logo}
          alt="todo-logo"
          width={180}
          height={180}
          className='mb-6'
        />
        <div className='w-[20] sm:w-[36rem] h-auto bg-slate-100 rounded-lg p-10 mb-4'>
          <form className='w-full h-full flex items-center justify-center relative flex-col' onSubmit={(e) => handleEntailmentRequest(e)}>
            <input placeholder='What needs to be done' maxLength={40} className='w-full h-full p-3 outline-none bg-transparent border-b-[1px] border-slate-300 text-[#9b9b9b]' >
            </input>
            <button type='submit' className='w-16 h-16 rounded-full bg-[#30CEF6] border-8 border-[#F0EFE9] absolute top-16 flex items-center justify-center'>
              <FaPlus className='text-white text-lg' />
            </button>
          </form>
        </div>
        <div className='w-[20rem] sm:w-[36rem] min-h-[100px] max-h-96 h-auto p-10 rounded-lg flex flex-col items-start justify-start bg-slate-100 text-sm font-semibold text-slate-400 overflow-y-scroll'>
          <ul className='w-full h-auto '>
            {todo.map((item, i) => {
              return (
                <div key={i} className='w-full h-auto flex items-center mb-4'>
                  <span className='mr-5'>{i + 1}</span>
                  <li onClick={(i) => complateTodo(i)} className={`cursor-pointer`}>{item}</li>
                  <div className=' ml-auto flex items-center justify-center '>
                    <FaTimes className='text-[#9b9b9b] text-sm transition-all ease-linear delay-75 hover:text-red-500  ml-auto cursor-pointer' onClick={(İ) => deleteTodo(i)} />
                  </div>
                </div>
              )
            })}
          </ul>
        </div>
      </main>
    </>
  )
}
